# Site settings
title: CitizenTrust
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Giving control to individuals of their rights to online privacy, data protection and free speech through research, education, advocacy and the provision of information and advice.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://citizentrust.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  citizentrust

# Build settings
markdown: kramdown
